<?php
/**
 * News tempalte for separate item
 *
 * @author Bulat
 */

/**
 * @var $this Magentostudy_News_Block_Item
 * @see Magentostudy_News_Block_Item
 */
?>
<?php $_newsItem = $this->helper('magentostudy_news')->getNewsItemInstance();?>
<div id="news_item_messages">
    <?php echo $this->getMessagesBlock()->getGroupedHtml()?>
</div>

<div>
    <h1> <?php echo $this->escapeHtml($_newsItem->getTitle())?></h1>

    <div>
        <?php echo $this->formatDate($_newsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM)?>|
        <?php echo $this->escapeHtml($_newsItem->getAuthor())?>
    </div>
</div>

<div>
    <?php if($iamgeUrl = $this->getImageUrl($_newsItem, 400)):?>
    <p>
        <img src="<?php echo $iamgeUrl?>" alt="<?php echo $this->escapeHtml($_newsItem->getTitle())?>">
    </p>
    <?endif;?>

    <div><?php echo $_newsItem->getContent()?></div>

    <div>
        <a href="<?php echo $this->getBackUrl()?>">
            <?php echo Mage::helper('magentostudy_news')->__('Return to list')?>
        </a>
    </div>
</div>