<?php

class Azazello_DBScript_Model_Ticket extends Mage_Core_Model_Abstract
{
    protected function _construct()
    {
        $this->_init('azazello_dbscript/ticket');
//        parent::_construct(); // TODO: Change the autogenerated stub
    }
}